### ISSUE TITLE
Give weight to DOM mutations (in addition to pure algo)

### ISSUE THREAD

**Issue by luwes** [luwes/js-diff-benchmark#13]
The test at the moment measures the algorithm but it doesn't correlate to real life where the number of DOM mutations can have a bigger impact than the algorithmic logic.

It would be interesting to see if giving weight (take more time) to these operations could simulate a real browser environment better.

Probably better start using playwright or puppeteer at that point
https://github.com/puppeteer/puppeteer
https://github.com/microsoft/playwright

**Comment by WebReflection** [comment]
it feels like we're going to re-implement js-framework-benchmark after all ... 😉

**Comment by luwes** [comment]
you're right, it's great it's a fast test at the moment. don't want to slow it down much. the weights might be something tough. stage0 is consistently the lowest in operations for the shuffle, I think it should give some benefit at least.

**Comment by WebReflection** [comment]
again, if it takes "forever" to figure out the least amount of operations, you can't win. I've used [Levenshtein distance](https://github.com/WebReflection/majinbuu#readme), the [Meyer's O(ND)](https://github.com/WebReflection/speedy-myers#readme), and these all look good on paper, but perform kinda poorly on DOM.

I agree that having real DOM engines in the mix makes sense, but I wouldn't expect much concrete changes in numbers.
