### ISSUE TITLE
Consider adding `random` shuffle in the mix

### ISSUE THREAD

**Issue by WebReflection** [luwes/js-diff-benchmark#2]
Another interesting test to put in the mix:

```js
diff(
    parent,
    parent.childNodes,
    parent.childNodes.sort(() => Math.random() - Math.random()),
    get,
    parent.lastElementChild
  );
```

### Warning

_snabdom_ here fails 1 out of 3 times so that tests should likely be put in `try/catch` and warn in red the test broke/didn't work.

You can give it a try with 1000 rows already, launch it few times and see _snabdom_ fall.

I might file an issue in there though ... or maybe they know already.

**Comment by luwes** [comment]
thanks for checking! 
the snabbdom script used here might not be 1 to 1 with the real thing.
I will see if I can find the issue later.

**Comment by tomByrer** [comment]
The lack of randomness in all speed tests irks me.  Thanks for requesting & looking into it guys!

**Comment by luwes** [comment]
`Array.sort()` is mutating right? is that okay in this case

**Comment by luwes** [comment]
oh yea that's a slice behind the scenes 😅
