### ISSUE TITLE
Fix Snabbdom assertions

### ISSUE THREAD

**Issue by luwes** [luwes/js-diff-benchmark#23]
2 assertions are failing for Snabbdom 

<img width="962" alt="Screen Shot 2020-04-17 at 7 38 22 PM" src="https://user-images.githubusercontent.com/360826/79622170-2af7c080-80e4-11ea-8bfe-5acc9f6a45ca.png">

**Comment by blankhart** [comment]
The issue is in the fast insertion path on [this line](https://github.com/luwes/js-diff-benchmark/blob/524c648aeac1feb14466949616adeb28904a6722/libs/snabbdom.js#L109), which assumes an append at `afterNode`.  Instead, that block should append at `a[start_i] || afterNode`:

```javascript
    if (start_i > end_i) { // old list exhausted; process new list additions
      for (; start_j <= end_j; start_b = b[++start_j]) {
        parent.insertBefore(start_b, a[start_i] || afterNode);  // not afterNode
      }
    }
```

**Comment by WebReflection** [comment]
@blankhart thanks!
