### ISSUE TITLE
jsperf case

### ISSUE THREAD

**Issue by dy** [luwes/js-diff-benchmark#30]
Here's jsperf template for insights:
https://jsperf.com/insertbefore-vs-udomdiff-vs-snabbdom-vs-spect/1

**Comment by WebReflection** [comment]
this is what I see, but _udomdiff_ is a library with a license, if you copy and paste it around, you need to put the license in place.

It's also not clear what is this issue about: the title doesn't tell anything, and the description doesn't provide any explanation.

![Screenshot from 2020-04-19 08-02-48](https://user-images.githubusercontent.com/85749/79680818-45c95280-8214-11ea-97ba-177c1b51ddec.png)
