### ISSUE TITLE
Note on Update every 10th row

### ISSUE THREAD

**Issue by ryansolid** [luwes/js-diff-benchmark#4]
I think it is good to know. And it is definitely a consideration for libraries in general. But I wanted to point out from a reactive standpoint I think this test doesn't matter for the list reconciler very much. Nested updates unless they replace the whole element avoid the list reconciler (which is why reactive is fast). From this perspective I think that makes udomdiff still the better choice for a reactive library?

EDIT: I see replace is the big one. Probably because doesn't do the shortcut there. I wonder how much code that'd take to remedy. And the scaling of append. Interesting. That deserves further investigation.

**Comment by luwes** [comment]
good point @ryansolid. I changed the test a little so the node is actually fully replaced so it has some effect on reconcile metrics. see here https://github.com/luwes/js-diff-benchmark/blob/9784a116a6a9e05eb3cb43197f6858ad65d3f668/src/bench.js#L270-L270
