### ISSUE TITLE
Correctness of the benchmark

### ISSUE THREAD

**Issue by Freak613** [luwes/js-diff-benchmark#41]
As I understand, results published in README are results from running tests on node.
After running benchmark multiple times on Chrome 89 with 6x CPU throttling I barely can get 3% difference between stage0 and udomdiff reconcilers, while results in node (and README) look like there is almost x3 slowdown difference between them.
Results between 5 of 6 libraries are very minimal, with only heckel having noticeable hit.
I would recommend to use only browser results, they do not change the winner, but can ease bad representation of other libraries. Also I think results in the browser are much more stable, especially with throttling, without hunting for randomized milliseconds in node.

<img width="1022" alt="Screenshot 2021-04-07 at 20 58 33" src="https://user-images.githubusercontent.com/9072673/113967196-5be56f80-97e5-11eb-8d5b-03cebd0dbc33.png">

**Comment by luwes** [comment]
Thanks for double checking @Freak613 ,
I'm fine with only adding these results as image in the readme, will approve PR.

I can't say 100% sure but it seems on the js-framework-benchmark stage0 is still the fastest and I noticed the fallout from this when Sinuous got updated in the bench 😅 
https://github.com/krausest/js-framework-benchmark/pull/858#issuecomment-787472913

**Comment by Freak613** [comment]
Created PR:
https://github.com/luwes/js-diff-benchmark/pull/42

**Comment by Freak613** [comment]
Thanks, updated readme makes more sense.
